export const ANIMATION_TIME = 5000;
export const DRAWER_WIDTH = '350px';
export const ZOOM_FACTOR = 1.15; 
export const MAGNIFYING_SIZE = 250;
export const SET_SIZES = {
  SMALL: '140',
  MEDIUM: '500',
  LARGE: '700'
};
export const TAKE_SNAPSHOT = 'TAKE_SNAPSHOT';
export const PRODUCTS_SNAPSHOT = 'PRODUCTS_SNAPSHOT';
export const OPEN_PRODUCT_DETAILS = 'OPEN_PRODUCT_DETAILS';
export const MESSAGE_DIRECTIONS = { IN: 'IN', OUT: 'OUT' }
export const OPEN_SHOPPING_CART = 'OPEN_SHOPPING_CART';
export const CLOSE_SHOPPING_CART = 'CLOSE_SHOPPING_CART';
export const CLOSE_PRODUCT_DETAILS = 'CLOSE_PRODUCT_DETAILS';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const REMOVE_PRODUCTS = 'REMOVE_PRODUCTS';
export const OPEN_CHAT = 'OPEN_CHAT';
export const RECOMMEND_PRODUCTS = 'RECOMMEND_PRODUCTS';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const CLOSE_CHAT = 'CLOSE_CHAT';

export const PRODUCTS_NOTIFIER_LIST = {
  SHOPPING_CAR: 'shopping-car',
  PRODUCTS: 'produtcs'
};
